find_path(LIKWID_INCLUDE_DIR likwid.h
    HINTS ${LIKWID_INSTALL_ROOT}/include)
find_path(LIKWID_INCLUDE_DIR
    NAMES "likwid.h"
    PATH_SUFFIXES "include" "include/likwid")

find_library(LIKWID_LIBRARY likwid
    HINTS ${LIKWID_INSTALL_ROOT}/lib)
find_library(LIKWID_LIBRARY
    NAMES "likwid"
    PATH_SUFFIXES "lib" "lib32" "lib64")


IF (LIKWID_INCLUDE_DIR AND LIKWID_LIBRARY)
    SET(LIKWID_FOUND TRUE)
ENDIF (LIKWID_INCLUDE_DIR AND LIKWID_LIBRARY)

IF (LIKWID_FOUND)
    set(likwid_INCLUDE_DIRS ${LIKWID_INCLUDE_DIR})
    set(likwid_LIBRARIES ${LIKWID_LIBRARY})

    # set HAVE_LIKWID for config.h
    set(HAVE_LIKWID ${likwid_FOUND})

    IF (NOT LIKWID_FIND_QUIETLY)
        MESSAGE(STATUS "Found Likwid: ${LIKWID_LIBRARY}")
    ENDIF (NOT LIKWID_FIND_QUIETLY)
ELSE (LIKWID_FOUND)
    IF (LIKWID_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find Likwid")
    ENDIF (LIKWID_FIND_REQUIRED)
ENDIF (LIKWID_FOUND)
